### PR TITLE
feat: interactive warning for packages in `pixi global install`

### PR DESCRIPTION
**Pull request by ruben-arts**
I've had helped to many people with `pixi global install pip`

This feels like a helpful temp fix. 

image

### CODE REVIEW

**Comment by olivier-lacroix** [comment]
Do you think the pip message should also point out pixi can install python packages without any need for pip in most cases?

**Comment by tdejager** [comment]
Seems like a good improvement!

**Comment by ruben-arts** [comment]
Good tip @olivier-lacroix, hopefully improved it!

**Comment by olivier-lacroix** [comment]
cool. thx @ruben-arts !

**Pull request merged**
