### PR TITLE
docs: Remove cache: true from setup-pixi

### PR DESCRIPTION
**Pull request by pavelzw**
This is the default now and doesn't need to be specified

### CODE REVIEW

**Review by baszalmstra — APPROVED** [review]
Amazing as always! 🥇 

Thanks!

**Comment by pavelzw** [comment]
How about in Basic Usage?

**Comment by baszalmstra** [comment]
Perhaps as an example? @ruben-arts WDYT?

**Comment by pavelzw** [comment]
I'm also thinking of just mirroring the complete README.md from setup-pixi and adding a

```md
- [ ] updated readme for pixi.sh
```

in the pull request template of setup-pixi.
This might make for a better docs experience overall...

**Comment by pavelzw** [comment]
I think `polarify` has a nice GHA integration. I could also add it as an example and describe what's happening under the hood a bit more.

**Comment by ruben-arts** [comment]
Yeah we would love the `setup-pixi` docs to be integrated in pixi.sh we also want to do this for `pixi-docker`. 
Could have it's own page, and be added in the navigation. Then we can link to it from the basic usage. 
Multiple examples would always help!

**Pull request merged**
