### PR TITLE
fix: start pwsh interactive instead of no-exit

### LINKED ISSUE #514: Powershell fails every prompt in pixi shell after cancelling (ctrl+c)
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

(see description)

### Issue description

* open powershell
* navigate to folder with a pixi.toml file
* `pixi shell`
* `sleep(1000)` (or any other long running command
* ctrl+c to cancel while it is still running
* press enter, observe how error code remains `-1073741510`. In my case the  oh-my-posh shell plugin also gets.. issues:
image

### Expected behavior

continue operating as normal

### PR DESCRIPTION
**Pull request by ruben-arts**
Closes #514

### CODE REVIEW

**Comment by melund** [comment]
This PR breaks the `pixi shell` command for me. It no longer activates, but just exits immediately.

**Comment by wolfv** [comment]
@baszalmstra also reported that this doesn't work for him ...

**Comment by ruben-arts** [comment]
Dammit, I wasn't able to test it yet on windows. So will have to try that later....

**Comment by baszalmstra** [comment]
I pushed a fix that seems to fix this issue for me locally!

**Comment by melund** [comment]
Now `pixi shell` works again. But this doesn't fix the original issue #514, which is back. 

If I do: 
``` 
pixi shell
sleep(1000) 
<crtl c> 
```
Then I end in a situation where PowerShell acts really weird. Almost like two shell are running on top of each other. All input gets garbled, and I can't really type anything sensible after that.

**Comment by ruben-arts** [comment]
I'm honestly lost on how we can improve this issue. Would love to get some help from powershell users!

**Comment by ruben-arts** [comment]
Close as this isn't the fix

**Pull request closed without merging**
