### PR TITLE
chore: bump to v0.18.0

### PR DESCRIPTION
**Pull request by ruben-arts**

### CODE REVIEW

**Comment by henryiii** [comment]
Will there be a GitHub release too?

**Comment by baszalmstra** [comment]
Yes, should be available very soon.

**Comment by henryiii** [comment]
Great, just making sure it wasn't a manual step that was forgotten. :)

**Comment by ruben-arts** [comment]
> Great, just making sure it wasn't a manual step that was forgotten. :)

No sorry, we're EU based and there were some steps left and to avoid merging a huge change without the ability to give support immediately made us postpone it to tomorrow morning.

**Comment by ruben-arts** [comment]
Its out!

**Comment by henryiii** [comment]
Great thanks! Homebrew should update soon: https://github.com/Homebrew/homebrew-core/pull/167888 (future update PRs will be automatically created)

**Comment by wolfv** [comment]
Thanks @henryiii! :)

**Pull request merged**
