### PR TITLE
fix: enable use of manylinux wheeltags once again

### PR DESCRIPTION
**Pull request by tdejager**
This boolean was filtering out the creation of manylinux wheel tags.

### CODE REVIEW

**Comment by wolfv** [comment]
Can we test this in some way to prevent regressions? Maybe with Rubens new integration tests?

**Comment by tdejager** [comment]
Sure we could test more, but this only adds more tags not less :)

**Review by baszalmstra — APPROVED** [review]

**Comment by liblaf** [comment]
I tested the installation of some PyPI packages on this PR. Here's the [result](https://github.com/liblaf/pixi-test/actions/runs/10577946363):

<details>

<summary> Results </summary>

| Package | pip | pixi | uv |
| --- | --- | --- | --- |
| confz | ✅ | ✅ | ✅ |
| dvc | ✅ | ✅ | ✅ |
| dvclive | ✅ | ✅ | ✅ |
| icecream | ✅ | ✅ | ✅ |
| jax | ✅ | ✅ | ✅ |
| jax[cuda12] | ✅ | ✅ | ✅ |
| matplotlib | ✅ | ✅ | ✅ |
| meshio[all] | ✅ | ✅ | ✅ |
| meshpy | ✅ | ✅ | ✅ |
| meshtaichi-patcher | ✅ | ✅ | ✅ |
| mkdocs | ✅ | ✅ | ✅ |
| mkdocs-material | ✅ | ✅ | ✅ |
| mkdocstrings[python] | ✅ | ✅ | ✅ |
| numpy | ✅ | ✅ | ✅ |
| pymeshfix | ✅ | ✅ | ✅ |
| pyright | ✅ | ✅ | ✅ |
| pytest | ✅ | ✅ | ✅ |
| pytest-benchmark | ✅ | ✅ | ✅ |
| pyvista | ✅ | ✅ | ✅ |
| ruff | ✅ | ✅ | ✅ |
| scipy | ✅ | ✅ | ✅ |
| sparse | ✅ | ❌ | ❌ |
| taichi | ✅ | ✅ | ✅ |
| trimesh[all] | ✅ | ✅ | ✅ |
| typeguard | ✅ | ✅ | ✅ |

</details>

[sparse](https://pypi.org/project/sparse/) still cannot be managed. There may be an upstream problem with [uv](https://github.com/astral-sh/uv).

**Comment by wolfv** [comment]
Yes, i think adding some pypi dep to a end-to-end test that uses these tags would be nice

**Comment by tdejager** [comment]
Thank you @liblaf!

**Comment by tdejager** [comment]
> Yes, i think adding some pypi dep to a end-to-end test that uses these tags would be nice

Added a single test, that should at least catch if we disable that boolean again :)

**Review by ruben-arts — APPROVED** [review]

**Pull request merged**
