### PR TITLE
fix: reenable reflinks

### PR DESCRIPTION
**Pull request by baszalmstra**
This PR reenables the use of reflinks. Although this might require some additional testing on different platforms I thought I'd create a PR to be able to start the process. :)

Since this is merged (https://github.com/mamba-org/rattler/pull/485) I think it should "just work"™

### CODE REVIEW

**Comment by baszalmstra** [comment]
Although Im not sure how to properly check this, on my windows dev-drive reflinks seem to work.

**Comment by ruben-arts** [comment]
To test this I propose: 
- Install all pixi examples
- remove part of the cache
- Reinstall all examples
- Run all `pixi run start`s in the examples
- Try to edit a python file in the cache to see if that breaks the environments and visa-versa
If this succeeds on all platforms I would be fine merging this. If there is any other tests you can come up with please share! Last time this failed in a really hard to understand way.

**Comment by baszalmstra** [comment]
> Reinstall all examples

Do you mean to first remove the `.pixi` folder

**Comment by ruben-arts** [comment]
> Do you mean to first remove the .pixi folder

Maybe that after first trying to reinstall and see if that broke anything.

**Comment by baszalmstra** [comment]
Here is a script that does the above.

```nu
# Navigate to the examples
> cd examples

# Clear all existing `.pixi` directories
> glob **/.pixi | each { rm -rf $in }

# Install all examples
> glob **/pixi.toml | each { pixi i --manifest-path $in }

# Delete content from cache directory
> rm -rf $"($env.PIXI_CACHE_DIR)/pkgs"

# Run a few examples 
> pixi run --manifest-path ctypes-factorial/pixi.toml start
> pixi run --manifest-path cpp-sdl/pixi.toml start
> pixi run --manifest-path flask-hello-world/pixi.toml start
> pixi run --manifest-path opencv/pixi.toml start
> pixi run --manifest-path pypi/pixi.toml start
> pixi run --manifest-path rerun_example/pixi.toml start
> pixi run --manifest-path turtlesim/pixi.toml start

# Clear all existing `.pixi` directories
> glob **/.pixi | each { rm -rf $in } | null

# Reinstall flask-hello-world and corrupt the cache.
> pixi install --manifest-path flask-hello-world/pixi.toml
>  echo 'assert(False, "BoOm I Br0k3 1t")' o>> $"($env.PIXI_CACHE_DIR)/pkgs/flask-2.3.3-pyhd8ed1ab_0/site-packages/flask/__init__.py"
> pixi run --manifest-path flask-hello-world/pixi.toml start
```

Essentially the last part checks if you are using reflinks or hardlinks by installing flask from cache, then corrupting a file in the cache. If hardlinks are used then running the command again should show you an error. Something like:

```
F:\examples\flask-hello-world\.pixi\envs\default\Lib\site-packages\flask\__init__.py:103: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(False, "BoOm I Br0k3 1t")
```

If reflinks are used this error should not be there because the file is copied when its edited.

This however does not check if the file is not copied..

**Comment by ruben-arts** [comment]
I'm pushing this one to the next release.

**Review by ruben-arts — APPROVED** [review]
Crazy big change, could you split it up in multiple pr's?

Haha I'm so funny. Works like a charm on fedora! Could you test it on mac @tdejager?

**Pull request merged**
