### PR TITLE
Refactoring of deserialise implementation for PyPiRequirement

### LINKED ISSUE #621: refactor PyPiRequirement to use `serde_untagged`
I stumbled upon `serde_untagged` and I think it would be very useful to remove some of the complexity of the `Deserialize` impl for `PyPiRequirement`. See:

https://github.com/prefix-dev/pixi/blob/dc5bab5b7c7d06925d3a799207adf66e77a864ba/src/project/python.rs#L134

Might be a nice "first issue".

### PR DESCRIPTION
**Pull request by marcelotrevisani**
Closes #621

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
Can you please take a look @baszalmstra ? I am not sure if it is what you want with that issue

**Comment by baszalmstra** [comment]
Hey @marcelotrevisani ! Thanks for working on this. 

This is not quite what I meant. [`serde-untagged`](https://crates.io/crates/serde-untagged) is a crate that makes deserialization of types that can be deserialized as different types (e.g. as a string, as a map, or as a bool) easier and with a nice error message. 

I just yesterday used this for another datastructure:

https://github.com/prefix-dev/pixi/blob/625d47513187e3a5f96aff0a6f33f93467fda264/src/project/manifest/system_requirements.rs#L80-L88

This supports deserializing the following:

```toml
[system-requirements]
libc = "1.2.3"
#or
libc = { version="1.2.3", family="glibc" }
```

**Comment by marcelotrevisani** [comment]
ah ok, gotcha, thanks for the explanation :)

**Comment by ruben-arts** [comment]
There are now some more example: https://github.com/search?q=repo%3Aprefix-dev%2Fpixi%20serde_untagged&type=code

Will close this PR for now as it isn't fixed yet.

**Pull request closed without merging**
