### PR TITLE
WIP Build packages right from `pixi`

### PR DESCRIPTION
**Pull request by wolfv**
First connection made with `rattler-build` - but still many question marks :)

### CODE REVIEW

**Comment by wolfv** [comment]
We still have to figure out the `$BUILD_DIR` env var @baszalmstra and I discussed.

**Comment by wolfv** [comment]
```toml
[project]
name = "xtensor"
version = "0.24.3"
description = "xtensor <3 pixi"
authors = ["Wolf Vollprecht <wolf@prefix.dev>"]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]

[tasks]
build_folder = "mkdir -p $PIXI_BUILD_FOLDER"
configure = {cmd = "cmake -S . -B $PIXI_BUILD_FOLDER -GNinja -DCMAKE_INSTALL_PREFIX=$PIXI_INSTALL_PREFIX -DBUILD_TESTS=ON", depends_on = ["build_folder"]}
test = {cmd = "cmake --build $PIXI_BUILD_FOLDER --target all && cmake --build $PIXI_BUILD_FOLDER --target test", depends_on = ["configure"]}
install = {cmd = "cmake --install $PIXI_BUILD_FOLDER", depends_on = ["configure"]}
clean = "rm -rf $PIXI_BUILD_FOLDER"

[build-dependencies]
cmake = "*"
ninja = "*"
cxx-compiler = "*"

[host-dependencies]
xtl = "*"
nlohmann_json = "*"
doctest = "2.4.11.*"

[dependencies]
xtl = "*"
nlohmann_json = "*"%
```

**Comment by hantmac** [comment]
Hi,
  Does `pixi build` support building Rust Python binding projects into Conda packages?

**Comment by wolfv** [comment]
It will support anything once it's ready, yes!

**Comment by wolfv** [comment]
TODO:

- [ ] Deal with deno task shell on Windows? Currently we're concatenating deno-task-shell commands and we just execute them with Bash. Can we pass a closure to rattler-build to execute deno task shell code?
- [ ] Calculate the hash properly?
- [ ] Specify more build options (noarch, script env, build number ...)

**Comment by ruben-arts** [comment]
Closing the for now to avoid confusing anyone

**Pull request closed without merging**
