### PR TITLE
fix: permissions for lint pr

### PR DESCRIPTION
**Pull request by ruben-arts**

### CODE REVIEW

**Comment by ruben-arts** [comment]
@orhun Any idea why it is not having the permissions?

**Comment by pavelzw** [comment]
Sometimes you need to add contents: read?

**Comment by orhun** [comment]
Looks like <https://github.com/amannn/action-semantic-pull-request/issues/233>

**Comment by ruben-arts** [comment]
I don't care anymore, removing the comment stuff for now.

**Review by wolfv — APPROVED** [review]

**Pull request merged**
