### PR TITLE
fix: Change global install activation script permission from 0o744 -> 0o755

### PR DESCRIPTION
**Pull request by zen-xu**
If the system administrator wants to install command-line tools via `pixi global install xxx`, the default permission does not allow others to execute.

### CODE REVIEW

**Review by ruben-arts — APPROVED** [review]
This makes sense to me. But maybe @baszalmstra did this with a purpose I'm not seeing. Would you give your approval?

**Comment by zen-xu** [comment]
This is like using `cargo` to install tools, the permissions are set to 755.

**Review by baszalmstra — APPROVED** [review]

**Comment by baszalmstra** [comment]
Looks good to me! Thanks!

**Comment by wolfv** [comment]
Awesome, thanks @zen-xu!

**Pull request merged**
