### PR TITLE
feat: upgrade to uv 0.3.4

### PR DESCRIPTION
**Pull request by tdejager**
Upgrade to 0.3.4, includes some changes we want to get in.

### CODE REVIEW

**Comment by manselmi** [comment]
FWIW uv 0.4.0 was just released. 😅

**Comment by tdejager** [comment]
> FWIW uv 0.4.0 was just released. 😅

Thanks! Yeah there release cycle is pretty rapid for sure!

Will probably try to keep doing these updates more regularly, let's try getting this one in first though!

**Comment by tdejager** [comment]
@ruben-arts @baszalmstra this one should be good for review, @ruben-arts I also reran and relocked all examples. Can I commit the updated locks in this PR?

**Comment by tdejager** [comment]
> @ruben-arts @baszalmstra this one should be good for review, @ruben-arts I also reran and relocked all examples. Can I commit the updated locks in this PR?

Fyi, @ruben-arts said: "Yes!"

**Review by ruben-arts — APPROVED** [review]
Looks good to me!

**Pull request merged**
