### PR TITLE
fix: trim channel url when filter packages_for_prefix_mapping

### PR DESCRIPTION
**Pull request by zen-xu**
Fixes: #1384

### CODE REVIEW

**Comment by zen-xu** [comment]
I found the channel of mapping source will end with "/", but the channel of RepoDataRecord won't

https://github.com/prefix-dev/pixi/blob/1ec1b90a4df20fa5555d431869e6335837bbf5ee/src/pypi_mapping/custom_pypi_mapping.rs#L102-L120

So `packages_for_prefix_mapping` always filter all packages for prefix_mapping

**Comment by zen-xu** [comment]
Still having some issues

**Comment by zen-xu** [comment]
> Looks very good! Thanks for spotting this.
> 
> Could you please add a small test for this usecase?

I don't know how to add a test for this usecase, can you provide some suggestions?

**Comment by nichmor** [comment]
> > Looks very good! Thanks for spotting this.
> > Could you please add a small test for this usecase?
> 
> I don't know how to add a test for this usecase, can you provide some suggestions?

sure!

you can take a look at this test:

https://github.com/prefix-dev/pixi/pull/1335/files#diff-a0d6a55fba5932c0cafe2e60f8573b8d7861f51c77e19b93100dfa8685f0ce5aR302

and add the same in `tests/solve_group_tests.rs` where you add some record with ending  `/` :
https://github.com/prefix-dev/pixi/pull/1335/files#diff-a0d6a55fba5932c0cafe2e60f8573b8d7861f51c77e19b93100dfa8685f0ce5aR333

but your mapping url don't have the `/` in channel.

So you will verify if we filter them right

**Comment by zen-xu** [comment]
@nichmor test is done

**Comment by nichmor** [comment]
> @nichmor test is done

Thanks for your work!

I've fixed the conflicts with main and changed a little the test to assert that we record qualifer for purl ( https://github.com/prefix-dev/pixi/pull/1391/files#diff-a0d6a55fba5932c0cafe2e60f8573b8d7861f51c77e19b93100dfa8685f0ce5aR409 ) 

Looks very good - I'm merging it.

**Pull request merged**
