### PR TITLE
feat: add trampoline for pixi global

### PR DESCRIPTION
**Pull request by Hofer-Julian**
TODO: 
- [x] Implement hardlinked trampoline to reuse the binary.

### CODE REVIEW

**Comment by nichmor** [comment]
to reiterate missing things:

- [ ] making hard links of trampoline when installing rather than duplicating them
- [ ] compressing trampoline binary itself to include a smaller sized thing in pixi
- [ ] testing

**Comment by nichmor** [comment]
> to reiterate missing things:
> 
> * [ ]  making hard links of trampoline when installing rather than duplicating them
> * [ ]  compressing trampoline binary itself to include a smaller sized thing in pixi
> * [ ]  testing

**Comment by Hofer-Julian** [comment]
## Testing:

### Preparation
- `cp -r ~/.pixi ~/.pixi-backup`

### Things we should test:
- Migration with `pixi global sync`
- Is everything there? Does `pixi global list` work? Are the binaries working?
- `pixi global install $your_favorite_binaries`
- `pixi global add $something`
- `pixi global remove $something`
- `pixi global edit` and `pixi global sync`
- `rm -rf ~/.pixi`
- `cp -r ~/.pixi-backup ~/.pixi`
- Delete some files in `~/.pixi/bin` and/or `~/.pixi/envs`
- Run `pixi global sync`
- Is the result expected?

**Comment by wolfv** [comment]
Here are a few things I tried:

1. Launch Python and check that it has no parent process other than `zsh`: Looks good!
```
$ pstree -s python
-+= 00001 root /sbin/launchd
 |-+= 02808 wolfv /Applications/iTerm.app/Contents/MacOS/iTerm2
 | \-+- 02810 wolfv /Users/wolfv/Library/Application Support/iTerm2/iTermServer-3.5.5 /Users/wolfv/Library/Application Support/iTerm2/iterm2-daemon-1.socket
 |   |-+= 67889 root /usr/bin/login -fpl wolfv /Applications/iTerm.app/Contents/MacOS/ShellLauncher --launch_shell
 |   | \-+= 67891 wolfv -zsh
 |   |   \--= 76396 wolfv /Users/wolfv/.pixi/envs/python/bin/python
```

2. Launch Python and press CTRL+C and CTRL+D, both work as expected
3. Check that we get the correct exit code: while this looks wrong, it's the same without the trampoline. We might want to double check on Linux and Win.

```
╰─$ ~/.pixi/envs/python/bin/python
Python 3.13.0 | packaged by conda-forge | (main, Oct 17 2024, 12:32:35) [Clang 17.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.exit(123)
╭─wolfv@pixi ~/Programs/pixi ‹feat/global-trampoline●›
╰─$ echo $?                                                                                                                                                                                                                                                               1 ↵
```

4. Installed and started Spyder: GUI program works as well!

**Review by ruben-arts — APPROVED** [review]

**Pull request merged**
