### PR TITLE
feat: add `description` field to `task`

### PR DESCRIPTION
**Pull request by jjjermiah**
first PR for the work for #1113 and part of #1434 

I believe next missing work would be some tests and I'm not entirely certain on how to update the `schema`. 

- [ ] Add tests 
- [ ] Update schema

note: I realized that the output for `task list` is now in a single line, so the description only prints after the `run` command if a description exists. 

image

### CODE REVIEW

**Comment by ruben-arts** [comment]
He @jjjermiah, thanks for implementing this!

You can update the schema, by changing the `schema/model.py` and add the description to some of the tasks in the `schema/examples/valid/full.toml`. 

I believe it would make sense to add the `description` to `Alias` as well. 

I'm also not sure what to do with `pixi task list` you could possible already make it print the descriptions with `pixi task list -v`, you can do this using: `if tracing::enabled!(Level::ERROR)` IIRC.

**Comment by jjjermiah** [comment]
@ruben-arts I've only added to the schema and I think I addressed the areas to add to the `Alias`. 

It looks like the schema GHA failed. Should I be running the `generate-schema` task and committing those changes as well?

**Comment by ruben-arts** [comment]
Ah yes, you also need to commit the modified schema.

**Comment by ruben-arts** [comment]
I think this feature would be much more useful if it also prints the description with `pixi task list`
What if it would print with the tasks and then for the described tasks it prints them line by line. 
For example:
```
> pixi task list
Tasks that can run on this machine:
-----------------------------------
- build-docs, bump, deploy-dev, deploy-latest,  generate-schema, install, lint, mike-serve, pypi-proxy, test, test-all, test-schema, toml-format, toml-lint
- docs: Serves the documentation locally and rebuilds on file changes.
- build: Builds pixi into a binary using cargo, but doesn't install it. 
```
Where you would use color to get more information. 

Another idea would be to use the `-v` option to get more info. e.g. listing all tasks with there command on verbose mode including the description.

```
> pixi task list -v
- docs: `mkdocs serve` "Serves the documentation locally and rebuilds on file changes."
- build: `cargo build` "Builds pixi into a binary using cargo, but doesn't install it."
- install: `cargo install --path . --locked`
etc.
```

What do you think?

**Comment by jjjermiah** [comment]
@ruben-arts thanks for describing those! 

Going through the codebase I think the first option is pretty straight forward

Given a setup of tasks like so:

```bash
> ./target/release/pixi task  --manifest-path examples/complex-pyproject/pyproject.toml ls -s
Tasks per environment:
----------------------
default  : hello
dev      : build, deploy, hello, serve, style, test, verify
publish  : build, deploy, hello, publish-pypi, publish-test, semver
py310    : hello, test
py311    : hello, test
py312    : hello, test
```

If only a handful of those have descriptions, the first option would look like: 

```bash
❯ ./target/release/pixi task  --manifest-path examples/complex-pyproject/pyproject.toml ls
Tasks that can run on this machine:
-----------------------------------
build, deploy, hello, publish-pypi, publish-test, semver, serve, style, test, verify

 - build           Builds the documentation                          
 - build           Builds the package using hatch                    
 - deploy          Deploys a release to GitHub                       
 - deploy          Deploys the documentation to GitHub Pages         
 - publish-pypi    Publishes the package to the main PyPI repository 
 - publish-test    Publishes the package to the test.pypi.org repository
 - serve           Serves the documentation on localhost             
 - test            Runs pytest with coverage
```

I think the second option would just use the same print code but add the `cmd` field and wrap the code behind an `if args.verbose` clause.

Does that look about right to you?

Side note:
- I'm wondering if the `--verbose` option might get confusing, between:
    - `pixi task --verbose list --verbose` 

what if we used `--detailed`?

**Comment by jjjermiah** [comment]
On another tangent, I might just be nitpicking my own implementation here but with example again for context:

```sh
./target/release/pixi task  --manifest-path examples/complex-pyproject/pyproject.toml ls
Tasks that can run on this machine:
-----------------------------------
build, deploy, hello, publish-pypi, publish-test, semver, serve, style, test, verify

 - build           Builds the documentation                          
 - build           Builds the package using hatch                    
 - deploy          Deploys a release to GitHub                       
 - deploy          Deploys the documentation to GitHub Pages         
 - publish-pypi    Publishes the package to the main PyPI repository 
 - publish-test    Publishes the package to the test.pypi.org repository
 - serve           Serves the documentation on localhost             
 - test            Runs pytest with coverage  
```

there could be ambiguity of which environment the duplicated tasks belong to: 
- i.e `build` and `deploy` 

so in the context of a collaborative project,

collaborator wants to know which task will deploy to github pages
--> runs `task ls` to get the descriptions and learns that its the `deploy` task 
--> would need to know to use `run -e docs deploy` 

this is obviously easily dealt with by not using similar names, and/or properly naming environments to be clear, but I wonder how a more complicated project might introduce ambiguity

<details>
<summary>ideas for solutions seem just as confusing </summary>

populating a (_colored_ <envs>) after the description if the taskname is duplicated

```sh
 - build           Builds the documentation (dev)
 - build           Builds the package using Hatch (publish)
 - deploy          Deploys the documentation to GitHub Pages (dev) 
 - deploy          Deploys a release to Github (publish)
 - publish-pypi    Publishes the package to the main PyPI repository
 - publish-test    Publishes the package to the test.pypi.org repository
 - serve           Serves the documentation on localhost
 - test            Runs pytest with coverage (dev, py310, py311, py312)
```

printing a table for detailed representation 

image


</details>

**that being said**, if this starts getting too complicated I'm game to keep it simple and leave this situation for another PR 

what do you think @ruben-arts

**Comment by ruben-arts** [comment]
Thanks for exploring solutions!
Yeah lets keep it simple in this first PR and improve the output later!

Is it ready from your side?

**Comment by ruben-arts** [comment]
You're able to use `tracing`'s level logic to determine the verbosity level and let your program behave differently. But it is not the best as it will possibly show more then you want.

**Comment by jjjermiah** [comment]
@ruben-arts think I worked it out on my end, let me know what you think!

**Review by ruben-arts — APPROVED** [review]
Thank you! I like it!

**Pull request merged**
