### PR TITLE
feat: add pixi run completion for fish shell

### PR DESCRIPTION
**Pull request by dennis-wey**
Add one more line to the fish script for code completion to support listing tasks in `pixi run`.

I didn't know how to add description information but as far as I saw for the other shells, it's not yet used there either.

Closes https://github.com/prefix-dev/pixi/issues/1191

### CODE REVIEW

**Comment by tdejager** [comment]
Hi! 

Thanks for the contribution, that would be a great addition, couple things need to be changed:

1. As is the command currently errors e.g I get this:
```bash
build build-docs bump bump-changelog deploy-dev deploy-latest docs generate-schema install lint mike-serve pre-commit-install pre-commit-run pypi-proxy run-all-examples run-all-examples-dev test test-all test-schema toml-format toml-lint
---> complete: -a: option requires an argument
```
This is because it needs to get the arguments from standard out.
2. It needs to handle proper error behavior: When `pixi task list` is run in a folder without a pixi.toml, this command will output an error to stderr and have a exit code of 1. This needs to be handled by ignoring that message. Bash and zsh have examples for it.
3. It needs to have delay the evaluation, now it will evaluate on the source of the script, so I think it needs quoting around the command.
4. It needs a completion per line I think, from my testing, rendering it into a string with spaces makes it consider it one command? Not sure about this one.
5. Last thing, guess its a bit tricky but, it should not autocomplete on `pixi run start run <TAB>` this should do nothing. This works for bash at least.

Should be close to (but not correct yet):
```
complete -c pixi -f -n "__fish_seen_subcommand_from run" -a "(pixi task list --machine-readable 2>&1 | string split ' ')"
```
But that does not handle 2, and 6 though.

For 6. chatgpt suggested something like:

```fish
# Function to check if 'run' is the first subcommand
function __fish_pixi_run_first_subcommand
    # Get the current command line input
    set -l cmd (commandline -opc)
    
    # Check if the command line is exactly 'pixi run' or starts with 'pixi run '
    if string match -q "pixi run" -- $cmd
        return 0
    end

    return 1
end
```

For the `-n` flag like:
```
complete -c pixi -f -n "__fish_pixi_run_first_subcommand" -a "(pixi task list --machine-readable 2>&1 | string split ' ')" 
```

But that does not seem to work alas...

**Comment by dennis-wey** [comment]
Thanks @tdejager for the pointers!

I did some changes:

2. For me the newest commit works with error suppression. But can you test if the behavior is as you would expect it?
3. Added that as well
4. `-a` accepts a single string of options devided by space. In my tests the commands get parsed correctly

**Regarding Point 5:** 
I'm not sure what we want to achieve here. Reading from the chat gpt commands:

- check on command is exactly `pixi run`
    - no false positives but we would loose completion for `pixi run -e dev <TAB>`
        - (maybe there is a way to forward the environment to `pixi task list`, but I don't think we should do this in this pr)
- check on command starts with `pixi run`
    - that doesn't help for `pixi run start run <TAB>`

Instead we could do something like `-n "__fish_seen_subcommand_from run; and not __fish_seen_run_multiple_times"`.
But the we should somehow filter out cases like `pixi run -e run <TAB>`. But even if we do we might still get false negatives when someone tries to use piping/combining commands.

Another thing is even without this pr we already have this issue:
`pixi run python --manifest-<TAB>` -> `pixi run python --manifest-path`

So having thought about that, do you think cases like `pixi run start run <TAB>` are worth adding this complexity?

Let me know what you think

**Comment by tdejager** [comment]
@dennis-wey yes this is great thanks! I don't want to block on 5., as its difficult to get right indeed and having the completion is just too nice t.b.h.

Last request, what do you think adding the complete command for the alias `r` as well, I use that mostly, don't know if that would give too many false positives. wdyt?

**Comment by dennis-wey** [comment]
@tdejager actually I didn't know that that one exists :D
Seems like it was also overlooked in the current auto-completion.

I added a regex pattern that `r` is treated the same way as `run`.

**Comment by tdejager** [comment]
> I'm also not sure why the tests are failing. COuld this be unrelated to my pr?

Not its because of the `setuptools` problems everywhere, hang on!

**Comment by tdejager** [comment]
Updating with main branch to fix CI.

**Review by tdejager — APPROVED** [review]

**Review by tdejager — APPROVED** [review]

**Pull request merged**
