### PR TITLE
refactor: Refactor channel add and remove CLI commands

### PR DESCRIPTION
**Pull request by olivier-lacroix**
Refactor channel add and remove CLI command into a common `AddRemoveArgs` struct with helper methods

### CODE REVIEW

**Review by baszalmstra — APPROVED** [review]

**Comment by ruben-arts** [comment]
Oehf this will conflict with what I did in #1683. What do you think of the change of `dependency_config` I did there?

**Comment by olivier-lacroix** [comment]
@ruben-arts I don't think so. This is looking at channel add / remove

**Comment by ruben-arts** [comment]
Sorry, disregard my comment. Didn't look good enough at the work!

**Comment by olivier-lacroix** [comment]
No worries @ruben-arts . better safe than sorry :-)

**Review by ruben-arts — APPROVED** [review]

**Pull request merged**
