### PR TITLE
feat: satisfiability for source packages

### PR DESCRIPTION
**Pull request by baszalmstra**

### CODE REVIEW

**Comment by tdejager** [comment]
@baszalmstra tried to fix satisfiabily test issue, but had to use multithreaded runtime not sure if there is a better way? Next the diagnostic seems off in snapshot?

Tested on ros workspace though and works like a charm!

**Comment by baszalmstra** [comment]
I restructured the test to use `rstest` instead of `insta::glob` this has the added benefit of running in parallel.

**Review by tdejager — APPROVED** [review]

**Review by tdejager — CHANGES_REQUESTED** [review]
Last thing could you maybe look into moving stuff into seperate crates? Like the GlobHashCache?

**Comment by baszalmstra** [comment]
I moved the `GlobHash` and `GlobHashCache` to `pixi_glob`. Maybe thats also useful for your work? However you only need to check the timestamps instead of the hashes I guess. But at least globbing might be useful!

**Review by tdejager — APPROVED** [review]

**Pull request merged**
