### PR TITLE
feat(config): `XDG_CONFIG_HOME` and `XDG_CACHE_HOME` compliance

### LINKED ISSUE #1049: $XDG_CONFIG_HOME on macOS has an unexpected behaviour
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
# on a macOS system, execute the following:
$ cat "change_ps1 = false" >> $HOME/.config/pixi/pixi.toml
$ pixi shell
# should not change one's prompt to include the environment name
```

### Issue description

My understanding is that `$XDG_CONFIG_HOME`, if unset, defaults to `$HOME/.config` [as per specifications](https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html).

However, I see that on macOS pixi searches at `INFO pixi::config: Global config not found at /Users/userid/Library/Application Support/pixi/config.toml`

I checked the package [xdg-base-dirs](https://pypi.org/project/xdg-base-dirs/), and it reports `~/.config` as the default on macOS as well.

### Expected behavior

If `$XDG_CONFIG_HOME` is set, then pixi should look for its configuration at that base directory.

Otherwise, it should use the default which is `$HOME/.config` on macOS.

### PR DESCRIPTION
**Pull request by chawyehsu**
Close #1049

### CODE REVIEW

**Review by baszalmstra — APPROVED** [review]

**Comment by pavelzw** [comment]
Can we have similar behavior for `$XDG_CACHE_HOME` for consistency?

**Comment by chawyehsu** [comment]
> Can we have similar behavior for `$XDG_CACHE_HOME` for consistency?

good idea!

**Comment by anjos** [comment]
Related to XDG compliance, I'm assuming that the installer will also respect these defaults?

**Comment by anjos** [comment]
I'm asking because the documentation for the installation is not really explicit about this: https://pixi.sh/latest/

**Comment by ruben-arts** [comment]
Could you also update the docs in : https://pixi.sh/latest/advanced/explain_info_command/#cache-dir

**Comment by ruben-arts** [comment]
He @anjos which installer did you mean? The rattler cache (the underlying installer in pixi) will also use it with this PR. But if you mean the the actual pixi binary this isn't changed by this PR.

**Review by ruben-arts — APPROVED** [review]
Thanks again @chawyehsu

**Comment by anjos** [comment]
Thanks to both of you!

@ruben-arts: what I mean was what was installed with the command line `curl -fsSL https://pixi.sh/install.sh | bash`.

**Comment by ruben-arts** [comment]
Just to verify, you mean that we install into `$HOME/.local/bin`? Because no we don't do that currently.

**Comment by anjos** [comment]
I apologise for the confusion - In short, I'm asking if pixi will also respect `$XDG_DATA_HOME` (typically `$HOME/.local/share`) for the location of `$PIXI_HOME/envs` and `$PIXI_HOME/bin`.  In this case, I'd expect that the command-line installation of the standalone pixi binary (`curl -fsSL https://pixi.sh/install.sh | bash`) should also do that instead of defaulting to `$HOME/.pixi`.

**Comment by chawyehsu** [comment]
It's easy to do so since we already support `$PIXI_HOME`, you can simply set `$PIXI_HOME=$XDG_DATA_HOME/pixi` and pixi will be installed to the directory you expect.

**Pull request merged**
