### PR TITLE
docs: add `mike` to the documentation and update looks

### PR DESCRIPTION
**Pull request by ruben-arts**

### CODE REVIEW

**Review by baszalmstra — APPROVED** [review]
Very cool!

**Comment by wolfv** [comment]
Is this one ready?

**Comment by ruben-arts** [comment]
@wolfv Still need to make the actual `gh-pages` branch

**Review by wolfv — APPROVED** [review]

**Comment by wolfv** [comment]
Looks good to me! If you have some time, maybe you can add the toggle thingy to rattler-build as well :)

**Pull request merged**
