### PR TITLE
fix: try to increase rlimit

### LINKED ISSUE #1551: Too many open files
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[project]
...
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]

[dependencies]
beautifulsoup4 = ">=4,<5"
chromadb = "<1"
coverage = ">=7.4.1,<7.5"
cyclonedx-bom = ">=3.11.7,<3.12"
datamodel-code-generator = ">=0.25.4,<0.26"
dateparser = ">=1.2.0,<1.3"
easyocr = ">=1.7.1,<1.8"
fastapi = ">=0.103.0,<0.104"
httpx = ">=0.26.0,<0.27"
ipython = ">=8.21.0,<8.22"
jupyter = ">=1.0.0,<1.1"
lxml = ">=5.1.0,<5.2"
openai = ">=1.35.3,<1.36"
openpyxl = ">=3.1.2,<3.2"
pandas = "2.*"
passlib = ">=1.7.4,<1.8"
pdbpp = ">=0.10.3,<0.11"
pdf2image = "1.16.*"
pixi-pycharm = ">=0.0.5,<0.1"
polars = ">=0.20.23,<0.21"
py-spy = ">=0.3.14,<0.4"
py7zr = ">=0.20.8,<0.21"
pydantic = ">=2.6.1,<2.7"
pyexcel = ">=0.7.0,<0.8"
pyexcel-xls = ">=0.6.2,<0.7"
pyexcel-xlsx = ">=0.6.0,<0.7"
pymongo = ">=4.6.1,<4.7"
pypdf = ">=4.0.2,<4.1"
pytesseract = ">=0.3.13,<0.4"
pytest = "<8" # https://github.com/TvoroG/pytest-lazy-fixture/issues/65
python = ">=3.12"
python-dotenv = ">=1.0.1,<1.1"
python-jose = ">=3.3.0,<3.4"
python-multipart = ">=0.0.7,<0.1"
sentence-transformers = ">=2.6.1,<2.7"
tabulate = ">=0.9.0,<0.10"
tesseract = ">=5.3.4,<5.4"
testcontainers = ">=4.4.0,<5"
thefuzz = ">=0.22.1,<0.23"
tiktoken = ">=0.6.0,<0.7"
transformers = ">=4.39.2,<4.40"
uvicorn = ">=0.27.0.post1,<0.27.1"
xmlschema = ">=3.2.0,<3.3"
xmltodict = ">=0.13.0,<0.14"
python-xxhash = ">=3.4.1,<3.5"
pyarrow = "<16" # pandas incompat
requests = "<2.32" # https://github.com/docker/docker-py/issues/3256
pytorch = "<2.3"
pytest-lazy-fixture = ">=0.6.3,<0.7"
loguru = ">=0.7.2,<0.8"
python-docx = ">=1.1.2,<1.2"
markdown = ">=3.6,<4"
pytest-xdist = ">=3.6.1,<3.7"
waitress = ">=3.0.0,<3.1"
pyright = ">=1.1.368,<1.2"
```

### Issue description

Running a large new environment for the first time, on macOS:

```shell
❯ pixi run python
  ⠂ default:linux-aarch6400:00:03] resolving conda
  ⠂ default:linux-64     [00:00:03] loading repodata
    ⠙ validate cache       [00:00:00] [━━━━━━━━━━━━━━──────] tesseract (+167)
    ⠙ download & extract   [00:00:00] [────────────────────]      0 B @ 0 B/s    scikit-learn (+100)
    ⠙ installing packages  [00:00:00] [────────────────────]     0/536 sentencepiece-python (+161)                                               × failed to instantiate a prefix for 'default'
  ├─▶ failed to link xmltodict-0.13.0-pyhd8ed1ab_0.tar.bz2
  ├─▶ failed to read 'index.json'
  ╰─▶ Too many open files (os error 24)
```

```
❯ wc -l pixi.toml
     105 pixi.toml
❯ wc -l pixi.lock
   25153 pixi.lock
❯ grep platform pixi.toml
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]
```

### Expected behavior

Should do fewer things in parallel so as to not go over macOS `ulimit -n`

### PR DESCRIPTION
**Pull request by baszalmstra**
This is an attempt to fix #1551

This PR does two things:

* Concurrent prefix installations share the same io concurrency limit to ensure we dont open too many files when running multiple installations concurrently.
* Pixi attempts to increase the soft rlimit to a "more sensible" value of 1024.

@wolfv, @ruben-arts  Would you be able to test this PR locally. I added a bunch of tracing to the rlimit setting. I wonder what happens on your machine.

### CODE REVIEW

**Comment by ruben-arts** [comment]
If I set the ulimit to `100` manually It tells me that it tried to overwrite it:
```
> ulimit -n 100

> pixi install
...
 INFO pixi::rlimit: Attempted to set RLIMIT_NOFILE to 1024 but was only able to set it to 100
...
```
Not sure if that would be expected but it at least keeps working for me.

**Comment by baszalmstra** [comment]
Mm since Im a Windows kinda guy Im not entirely sure how this is supposed to work. @wolfv Maybe you can help me out here.

Do you always see that info statement @ruben-arts ? Or did you have to use `-v`? It should not appear if you dont use `-v`.

**Comment by wolfv** [comment]
let me try with the large environment once again! :)

**Comment by wolfv** [comment]
Looks good! Old pixi version was consistently failing on ros2-nav2, but the build of this PR works like a charm! :)

Screenshot 2024-08-10 at 18 43 29

**Comment by baszalmstra** [comment]
If you run the command with -v does it also tell you something about the rlimit?

**Comment by wolfv** [comment]
Yes! Similar to Ruben I got something like CB 1024

**Review by ruben-arts — APPROVED** [review]
It seems to be fine for me

**Pull request merged**
