### PR TITLE
Improve looks: auto scale download bar

### PR DESCRIPTION
**Pull request by ruben-arts**
Had issues with it as the default size was to big for the default size of a linux terminal

### CODE REVIEW

**Comment by baszalmstra** [comment]
I explicitly set it to a value because otherwise the bar jumps if any of the other fields increase or decrease in size..

**Comment by ruben-arts** [comment]
@baszalmstra Hmmm not sure what is the best solution then. Maybe making it so small it is atleast working on the default size?

**Comment by baszalmstra** [comment]
Ideally the upstream library we use handles this better. https://github.com/console-rs/indicatif

For now I would prefer to make the bar smaller to make sure it fits better. WDYT?

**Comment by ruben-arts** [comment]
Yeah I think I was to the first guy to point out I hated the rescaling issue, and now in reintroduced it myself.... So the small version would be good for now!

**Review by baszalmstra — APPROVED** [review]

**Pull request merged**
