### PR TITLE
fix: forgot to configure `allow_insecure_host` when resolve_pypi

### PR DESCRIPTION
**Pull request by zen-xu**
I'm sorry I missed this point in #2521 @_@

### CODE REVIEW

**Comment by zen-xu** [comment]
@tdejager can you review this pr?

**Comment by ruben-arts** [comment]
Could you help us how we can test this PR, we merged the last one assuming it all worked for you but we couldn't figure out how to recreate it.

**Comment by wolfv** [comment]
Maybe you can set the pypi host to `https://expired.badssl.com/` and check the error? It should not fail with an SSL error but something else indicating that this is not a real pypi host :)

**Comment by ruben-arts** [comment]
It would be great to have a test for this, as I don't want to run this myself on every release.

**Comment by zen-xu** [comment]
> It would be great to have a test for this, as I don't want to run this myself on every release.

It is indeed somewhat difficult to verify this logic through tests

**Comment by zen-xu** [comment]
@ruben-arts test is done, can it be merged?

**Review by ruben-arts — APPROVED** [review]
Thank you!

**Pull request merged**
