### PR TITLE
fix: add a file guard to indicate if an environment is being installed

### LINKED ISSUE #1577: `exec` broken after aborted environment creation
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

Run any `pixi exec` and abort during environment creation, then re-run, e.g.:

```
❯ pixi exec -s 'tesseract<5' tesseract ...
  × failed to execute 'tesseract'
  ╰─▶ No such file or directory (os error 2)
```

### Issue description

When environment creation is aborted during `exec`, it can't be resumed

### Expected behavior

Should resume/recreate environment needed to run `exec`

### PR DESCRIPTION
**Pull request by baszalmstra**
Fixes #1577 

This adds a `.guard` file to the prefix which is locked using advisory guards and records the state of the environment. This allows detection if the installation of an environment was aborted and also ensures that if two processes run concurrently they will not interfere.

### CODE REVIEW

**Review by tdejager — CHANGES_REQUESTED** [review]
Could you move prefix_guard to utils?

**Comment by wolfv** [comment]
Should we do this in rattler?

**Comment by baszalmstra** [comment]
> Should we do this in rattler?

Yeah but Im not entirely sure about the API yet, so experimenting here for now. :)

**Comment by wolfv** [comment]
I think this would be great in a high level transaction api

**Comment by wolfv** [comment]
But fine to have it here for now, of course

**Review by tdejager — APPROVED** [review]

**Pull request merged**
