### PR TITLE
docs: Replace build with uv in pybind11 example

### PR DESCRIPTION
**Pull request by alvgaona**
It is much faster than the `build` Python package; `uv` is written in Rust so it makes sense.

### CODE REVIEW

**Comment by alvgaona** [comment]
With build and without environments installed:

image

With build and with environments already installed:

image

**Comment by alvgaona** [comment]
Now with uv and without environments (~30s):

image

With uv and with envs already installed (~12s):

image

**Comment by alvgaona** [comment]
> Looks good.
> 
> Could you please:
> 
> * fix pre-commit
> * get uv from conda forge instead of pypi

Will do!

**Comment by alvgaona** [comment]
@Hofer-Julian I think the `pre-commit` check is broken in every PR. Not just this one.

```
typecheck-tests..........................................................Failed
- hook id: typecheck-tests
- exit code: 127

⠁                                                                               
⠁ updating environment 'lint'                                                   
⠁ updating environment 'lint'                                                   
⠁                                                                               
⠁ activating environment                                                        
⠁ activating environment                                                        
typecheck-tests: command not found
```

**Comment by Hofer-Julian** [comment]
> @Hofer-Julian I think the `pre-commit` check is broken in every PR. Not just this one.
> 
> ```
> typecheck-tests..........................................................Failed
> - hook id: typecheck-tests
> - exit code: 127
> 
> ⠁                                                                               
> ⠁ updating environment 'lint'                                                   
> ⠁ updating environment 'lint'                                                   
> ⠁                                                                               
> ⠁ activating environment                                                        
> ⠁ activating environment                                                        
> typecheck-tests: command not found
> ```

Oh, thanks for the notice.
Should be fixed on main soon!

**Comment by Hofer-Julian** [comment]
I tried your PR locally and it fails with:

```
✨ Pixi task (build in build): python -m uv build
/var/home/julian/Projekte/github.com/prefix-dev/pixi-1/examples/pybind11/.pixi/envs/build/bin/python: No module named uv
```

Does it work for you locally?

**Comment by alvgaona** [comment]
> I tried your PR locally and it fails with:
> 
> ```
> ✨ Pixi task (build in build): python -m uv build
> /var/home/julian/Projekte/github.com/prefix-dev/pixi-1/examples/pybind11/.pixi/envs/build/bin/python: No module named uv
> ```
> 
> Does it work for you locally?

Yes! You were right. Just fixed it in the last commit. We're now using the command directly instead of the Python module. Good catch!

**Comment by alvgaona** [comment]
@Hofer-Julian it's ready 😅

**Comment by Hofer-Julian** [comment]
> @Hofer-Julian it's ready 😅

Awesome!

Will check it out tomorrow 😊

**Review by Hofer-Julian — APPROVED** [review]
Works like a charm.

I also tested the wheel locally, and it adds as it should :)

**Pull request merged**
