### PR TITLE
chore: use new `Installer` from rattler

### PR DESCRIPTION
**Pull request by baszalmstra**
This PR removes a whole bunch of code to install environments to use the `Installer` introduced in https://github.com/mamba-org/rattler/pull/664

### CODE REVIEW

**Comment by ruben-arts** [comment]
This looks good and feels even faster!

A Nitpick I found was the "flickering" of the `update prefix` on linux:
[Screencast from 2024-05-27 09-40-50.webm](https://github.com/prefix-dev/pixi/assets/12893423/3d77a3cd-d6b1-48cc-80d9-7ea0885cebd7)

I would also call it `installing packages` or something similar as I believe `prefix` is jargon.

**Comment by ruben-arts** [comment]
```
> pixi install
  ✔ validate cache       29 packages in 6.209346807s
  ✔ update prefix        took 6.898556135s                                                                                                                                                                ✔ The default environment has been installed.
```
If we improve the resulting timers I think this could be nice to keep the output.

**Comment by baszalmstra** [comment]
@ruben-arts I fixed the formatting of durations:

image

Changed the text to `installing packages`.

Im not sure how to solve the flickering. Some of the installation steps are just blazingly fast..

**Comment by ruben-arts** [comment]
image
What is the download counting format doing for `resolving conda`?

**Review by ruben-arts — APPROVED** [review]

**Pull request merged**
