### PR TITLE
feat: use named environments (only "default" for now)

### PR DESCRIPTION
**Pull request by ruben-arts**
Now the environments would be put in:

```
pixi/.pixi
└── envs
    └── default
        ├── bin
        ├── ...
        └── prefix  <--- prefix file
```

### CODE REVIEW

**Comment by wolfv** [comment]
I like the change but do we have to think about a migration strategy for existing users / envs?

**Review by baszalmstra — APPROVED** [review]

**Comment by pavelzw** [comment]
This will probably also lead to similar problems as https://github.com/prefix-dev/setup-pixi/issues/66 and https://github.com/prefix-dev/setup-pixi/issues/35...

**Comment by wolfv** [comment]
@pavelzw should we make the pixi version part of the cache key? Could that help?

**Comment by pavelzw** [comment]
Yeah that would help although `latest` is not really ideal for caching... we could either get the output of `pixi --version` or just use the SHA if the downloaded binary

**Comment by pavelzw** [comment]
https://github.com/prefix-dev/setup-pixi/pull/67

**Pull request merged**
