### PR TITLE
chore: sort pixi toml

### PR DESCRIPTION
**Pull request by Hofer-Julian**
Would be nice to have automation for that like we have for Cargo.toml

### CODE REVIEW

**Comment by ruben-arts** [comment]
Please automate this otherwise I'm going to have opinions.

**Comment by Hofer-Julian** [comment]
> Please automate this otherwise I'm going to have opinions.

Turns out taplo can do that 🎉

**Comment by Hofer-Julian** [comment]
I also removed cargo-sort. I don't see that it adds much to the more general `taplo` and I would like to avoid having two formatters fighting each other.

**Comment by ruben-arts** [comment]
Is this now run in CI?

**Comment by Hofer-Julian** [comment]
> Is this now run in CI?

I thought I checked that, but it doesn't. Nice find!
Will fix that in a bit.

**Comment by Hofer-Julian** [comment]
@ruben-arts it is now run in CI via pre-commit

**Comment by ruben-arts** [comment]
One nit pick, our `pixi init` format will not align with the key order. Might be good to change that to :sweat_smile:

**Comment by Hofer-Julian** [comment]
> One nit pick, our `pixi init` format will not align with the key order. Might be good to change that to 😅

Yeah, that should be relatively easy to do.

Same with `pixi add`, but here we might annoy users when we format their tables.

**Comment by Hofer-Julian** [comment]
I would prefer a follow-up PR for that, though. This one is already big enough, IMO. Agreed?

**Review by ruben-arts — APPROVED** [review]

**Pull request merged**
