### PR TITLE
fix: For installing from a lock file without doing a solve beforehand

### PR DESCRIPTION
**Pull request by tdejager**
Because of caching, the credentials were not available when a solve was
skipped. This makes sure the username and potentially password are
available for pulling from the registry.

More details are in this issue: https://github.com/prefix-dev/pixi/issues/1374#issuecomment-2138874996

### CODE REVIEW

**Comment by ruben-arts** [comment]
Nice find, how hard would it be to create a test for this?

**Comment by tdejager** [comment]
> Nice find, how hard would it be to create a test for this

First you need an external private registry if you want to rely on our own gcp instance being up,otherwise you need a proxy for pypi or something.
Second, a way to programatically clear the cache or ignore it?
Finally, a way to delete the `.pixi` folder.

I think that would be enough.

**Comment by ruben-arts** [comment]
Do you think it's worth adding it now?

**Comment by tdejager** [comment]
> Do you think it's worth adding it now?

I'll try and make it :)

**Comment by tdejager** [comment]
I'm thinking now it's somewhat hard to make a test because I need a global installation of keyring. This would make the test only runnable from a pixi env (with keyring) or when globally installed. So a `cargo t` without the global keyring installation would fail. At this point, I don't really think that's worth it for now :) wdyt @ruben-arts ?

**Comment by tdejager** [comment]
Verification that it works for azure: https://github.com/prefix-dev/pixi/issues/1374#issuecomment-2140544091

**Review by ruben-arts — APPROVED** [review]

**Pull request merged**
