### PR TITLE
fix: check if files are same in `self-update`

### LINKED ISSUE #1171: `pixi self-update` fails on symlink-ed home directory
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

—

### Issue description

When I run:

```shell
pixi self-update
```

I get the following output:

```
  × pixi is not installed in the default location:
  │ 
  │ - Default pixi location: /users/apoorvkh/.pixi/bin/pixi
  │ - Pixi location detected: /nfs/home/apoorvkh/.pixi/bin/pixi
```

My `$HOME` is `/users/apoorvkh`. But this is actually a bit of a red herring, since I think `/users/apoorvkh` is a symlink to `/nfs/home/apoorvkh`.

`pixi self-update --force` does work, but I just wanted to flag this edge case. Thanks!

### Expected behavior

—

### PR DESCRIPTION
**Pull request by apoorvkh**
`self-update` checks if the Pixi binary matches the default filepath. Instead of checking if paths are equal, we should check if files are same in `self-update`.

This should resolve this issue:
```
  × pixi is not installed in the default location:
  │ 
  │ - Default pixi location: /users/apoorvkh/.pixi/bin/pixi
  │ - Pixi location detected: /nfs/home/apoorvkh/.pixi/bin/pixi
```

which could be caused by using symlinks or case-insensitivity in Windows, etc.

Fixes #1171 and maybe #2059

### CODE REVIEW

**Comment by ruben-arts** [comment]
Thank you this looks good to me! What makes this a Draft PR?

**Comment by apoorvkh** [comment]
Draft PR because I just wanted to run the CI! I haven't yet manually tested it for the case in #1171 .

**Comment by apoorvkh** [comment]
But now I have tested it... and I am still getting the same error when I run `pixi self-update`.

```
  × pixi is not installed in the default location:
  │ 
  │ - Default pixi location: /users/apoorvkh/.pixi/bin/pixi
  │ - Pixi location detected: /nfs/home/apoorvkh/.pixi/bin/pixi
```

For the record, there is a symbolic link from `/users/` to `/nfs/home`. `same_file::is_same_file` is supposed to handle symlinks (see their [relevant tests](https://docs.rs/same-file/latest/src/same_file/lib.rs.html#531-559)).

**Comment by apoorvkh** [comment]
Okay did some testing. I think this implies the fix in my PR works!

---

When I use (the official) `pixi=0.30.0`, I get the same error as before.

```
❯ pixi self-update
  × pixi is not installed in the default location:
...
```

But when I do `pixi self-update --force`, I get an error:
```
❯ pixi self-update --force
thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.12.5/src/async_impl/client.rs:1901:38:
Client::new(): reqwest::Error { kind: Builder, source: Os { code: 13, kind: PermissionDenied, message: "Permission denied" } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

(This error does not occur when I use e.g. `pixi=0.25.0`.)

---

When I run `pixi self-update --force` from this PR's binary, I get that `PermissionDenied` error directly.
Since we don't see the "not installed in the default location" error message, I think our patch was successful.

I have no idea why there is a `PermissionDenied` error (my `pixi` binary has `rwx r-x r-x` permissions), but I think that is outside the scope of this immediate PR.

**Review by baszalmstra — APPROVED** [review]

**Review by ruben-arts — APPROVED** [review]
Thank you @apoorvkh !

**Pull request merged**
