### PR TITLE
feat: add progress reporter for build

### PR DESCRIPTION
**Pull request by tdejager**
This PR adds the first step of adding progress reporting for the pixi build progress. This creates some reporter traits
that can be used to report progress, but only implements noop reporters. Will implement actuall reporting of progress in subsequent PR.

### CODE REVIEW

**Comment by tdejager** [comment]
You are right it would probably need to be passed into the `build_source_record` functions and such.

**Comment by tdejager** [comment]
Changed this.

**Review by baszalmstra — APPROVED** [review]

**Comment by tdejager** [comment]
I added an allow is that alright?

**Comment by baszalmstra** [comment]
jeppers!

**Pull request merged**
