### PR TITLE
fix: prefix_file rename

### PR DESCRIPTION
**Pull request by ruben-arts**
fixes: #946 

Users still need to delete the `.pixi/envs/default/prefix` file manually after updating if it forms an issue for their `solara` installation

### CODE REVIEW

**Comment by baszalmstra** [comment]
Couldnt we not place this file in the `.pixi` folder instead of in the environment folder?

**Comment by ruben-arts** [comment]
> Couldnt we not place this file in the `.pixi` folder instead of in the environment folder?
We previously discussed to keep the file close to the environment. So yeah we could but I don't remember why we decided to do it this way.

**Comment by wolfv** [comment]
@baszalmstra I think it should ideally be placed in the `conda-meta` folder. We seem to have a bug where `rattler` thinks all files in teh conda-meta folder are JSON though. 

Conda does put a `history` and a `urls.txt` file there that also record some additional metadata.

**Comment by wolfv** [comment]
@ruben-arts I think you could try moving this file into `conda-meta` now. As long as it doesn't end with `.json` it should be OK.

**Review by wolfv — APPROVED** [review]

**Pull request merged**
