### PR TITLE
feature: allow specifying the environment in shell-hook

### LINKED ISSUE #719: `pixi shell` / `pixi shell-hook` needs to run in specified environment

### PR DESCRIPTION
**Pull request by ruben-arts**
Now you can do:
```
pixi shell-hook -e prod
pixi shell-hook --manifest-path ~/project/pixi.toml
pixi shell-hook --locked
pixi shell-hook --frozen
```

closes #719

### CODE REVIEW

**Review by baszalmstra — APPROVED** [review]
LGTM!

We wanted to not advertise the shell-hook script which is why we hid the option from the cli initially. You reverted that change. Was that intentional?

**Comment by ruben-arts** [comment]
@baszalmstra Yes, it didn't feel right to me to have a hidden cli command. My plan is to either support a feature or not allow the use at all. Otherwise people get inconsistent ux based on if the check he issues or not. To slim down the CLI my personal preference would be to make it a `--hook` flag for the `pixi shell`.

**Comment by wolfv** [comment]
I'd also be fine with `shell --hook` for what its worth.

**Review by wolfv — APPROVED** [review]

**Comment by baszalmstra** [comment]
Id be opposed to that as it drastically changes what the command does. I prefer the current naming scheme.

**Pull request merged**
