### PR TITLE
fix: reduce io concurrency

### PR DESCRIPTION
**Pull request by baszalmstra**
This PR tries to implement a better IO concurrency using https://github.com/conda/rattler/pull/980 . We have to test whether this improves performance before merging.

### CODE REVIEW

**Comment by baszalmstra** [comment]
On my local machine running `pixi install` with the `.pixi` folder removed takes:

`+- 44 seconds` with latest pixi.
`+- 34 seconds` with this PR.

**Comment by wolfv** [comment]
@baszalmstra are you using DEVDRIVE?

**Comment by baszalmstra** [comment]
Yes, both cache and target folder are on my devdrive. On an nvme ssd.

**Comment by ruben-arts** [comment]
Test results for this toml file:
```toml
[project]
channels = ["https://prefix.dev/conda-forge"]
name = "hard-to-install"
platforms = ["osx-arm64", "linux-64", "win-64"]

[dependencies]
rust = ">=1.83.0,<1.84"
scipy = ">=1.14.1,<2"
```
And the following command, assuming `pixi` is the one from this pr and `~/.pixi/bin/pixi` is the latest release:
```shell
hyperfine -p "pixi clean" "pixi install" "~/.pixi/bin/pixi install" -r 3
```

### `osx-arm64`
 TODO 
### `win-64`
 TODO 
### `linux-64`
 TODO

**Review by ruben-arts — APPROVED** [review]

**Pull request merged**
