### PR TITLE
refactor: delay channel config url evaluation

### PR DESCRIPTION
**Pull request by baszalmstra**
Uses the `NamedChannelOrUrl` type from `rattler` to delay channel url evaluation.

### CODE REVIEW

**Comment by ruben-arts** [comment]
fixed the tests in https://github.com/baszalmstra/pixi/pull/3

**Comment by wolfv** [comment]
This is great. Does this also mean we get relative file paths channels as relative to the pixi.toml now? :)

**Comment by baszalmstra** [comment]
Thanks @ruben-arts !

Im not quite done though. There are more uses that I wanna take care of.

**Comment by ruben-arts** [comment]
Great! Will put it on draft for the overview.

**Comment by wolfv** [comment]
For reference - the issue about relative channel paths: #1159

**Review by ruben-arts — APPROVED** [review]
Looks good to me

**Review by tdejager — APPROVED** [review]

**Pull request merged**
