### PR TITLE
feat: Make project table optional for `pyproject.toml` manifests

### PR DESCRIPTION
**Pull request by olivier-lacroix**
This Fixes https://github.com/prefix-dev/pixi/issues/1687 and https://github.com/prefix-dev/pixi/issues/1207 by keeping the `[project]` table optional in `pyproject.toml`.

The `[project]` table had been made mandatory to make sure a name was defined. Now, the project name is read from, in order of priority
 - the `[tool.pixi.project]` table
 - the `[project]` table
 - the `[tool.poetry]` table

The same is done for project description, version and authors.

During init, if the name cannot be read from the `[project]` table or the `[tool.poetry]` table, a default name (inferred from the directory name) is added to the `[tool.pixi.project]`

This PR also refactors handling of `pyproject.toml`: both pixi and non-pixi `pyproject.toml` are now read into the same `PyProjectManifest` struct, with existence checking of the `[tool.pixi.project]` table managed outside of serde when necessary.

### CODE REVIEW

**Review by ruben-arts — APPROVED** [review]
Thanks !! Looks good to me! And works like a charm.

**Comment by ruben-arts** [comment]
Asked @tdejager for another quick review.

**Review by tdejager — APPROVED** [review]

**Review by tdejager — CHANGES_REQUESTED** [review]
LGTM! The only thing I would change, is maybe if the name does not exist add it to the `pyproject` `project` table instead of the `tool.pixi` this makes it more standard-compliant. The only downside I can see is if you want to **not** use that name for a wheel build, but that would be pretty strange. WDYT @olivier-lacroix ?

**Comment by tdejager** [comment]
With some closer look, it seems to be a bit difficult to do this, I would like it but lets postpone, I'll approve and merge as is for now.

**Review by tdejager — APPROVED** [review]

**Comment by olivier-lacroix** [comment]
Thx @tdejager ! Maybe useful to have @pavelzw thoughts on this as well: I think I remember him not liking pixi imposing the creation of that table.

I do not see any difficulty in implementing it though: if `project.name` does not exist, this means there is no project table at all (as the field is mandatory), so we can 'just' insert it before the `[tool.pixi]` section. Or am I missing something?

**Pull request merged**
