### PR TITLE
add binary install commandos

### LINKED ISSUE #70: Document installation from binaries
Thanks a lot for working and open sourcing pixi!

It would be nice if the installation from binaries (that are available in the GitHub release) was documented in the README, for people that are not familiar with Rust/Cargo.

### PR DESCRIPTION
**Pull request by ruben-arts**
closes #70

### CODE REVIEW

**Comment by traversaro** [comment]
Thanks @ruben-arts !

**Comment by ruben-arts** [comment]
@wolfv What would be a nice replacement for the Macos version?

**Comment by wolfv** [comment]
I think we could install into `~/.pixi/` and tell the user to add it to the PATH (since they'd need it anyways for the shims?

**Comment by ruben-arts** [comment]
This is now completely rewritten into an install script for the systems that can easily be fetched using a web get a tool like curl. 

To test it use on linux:
```bash
curl -fsSL https://raw.githubusercontent.com/prefix-dev/pixi/docs/add_binary_install_command/scripts/install.sh | bash
```
or on windows:
```powershell
iwr -useb https://raw.githubusercontent.com/prefix-dev/pixi/docs/add_binary_install_command/scripts/install.ps1 | iex
```

**Comment by ruben-arts** [comment]
@traversaro Added a small section for the uninstall

**Comment by traversaro** [comment]
Thanks!

**Pull request merged**
