### PR TITLE
feat: turn on execution of link scripts

### PR DESCRIPTION
**Pull request by ruben-arts**
fixes: #1573 

Reasoning to activate it: https://github.com/mamba-org/rattler/pull/574#issuecomment-2012509459

### CODE REVIEW

**Comment by baszalmstra** [comment]
I dont think we should just activate these because its a security risk. 

Bun does this by warning users it didnt run activation scripts and allowing a special command to enable them. I think a user should explicitly opt in to this feature when they install a project.

**Comment by ruben-arts** [comment]
I'm not against your proposal but the explanation from wolf in the linked comment felt like it was discussed with you. 

Would we need to build this prompting logic into rattler? As the rest now gets sent there and I believe pixi doesn't know about the scripts before they "should have run" as that all happens in the install step.

**Comment by baszalmstra** [comment]
We discussed this for rattler-build only. 

We have to expose from rattler which scripts were/werent executing during the installation. We can do the user interaction completely in pixi.

**Comment by ruben-arts** [comment]
Should we also do it for the activation scripts then?

**Comment by baszalmstra** [comment]
Preferably yeah although that might be a much worse ux.

Perhaps something like "pixi trust" makes sense? Where you explicitly trust a project?

**Comment by ruben-arts** [comment]
I guess that would work. I'm just afraid it will scare a lot of people. Might need it to link to some documentation and print the script that it would try to run.

**Comment by ruben-arts** [comment]
Closing for above reasons

**Pull request closed without merging**
