### PR TITLE
refactor: Remove unused fetch_sparse_repodata

### PR DESCRIPTION
**Pull request by olivier-lacroix**

### CODE REVIEW

**Comment by baszalmstra** [comment]
Woops! I accidentally left that in!

**Review by baszalmstra — APPROVED** [review]

**Comment by olivier-lacroix** [comment]
aha no worries @baszalmstra ! It appears Gateway does not need to be stored in an `Arc`, given it already wraps one?

**Comment by olivier-lacroix** [comment]
Shouldn't gateway be used as well in `cli/global` @baszalmstra ?

**Comment by baszalmstra** [comment]
> aha no worries @baszalmstra ! It appears Gateway does not need to be stored in an `Arc`, given it already wraps one?

Correct! 👍 

> Shouldn't gateway be used as well in `cli/global` @baszalmstra ?

Yea, I just didnt get around to implementing proper feedback yet. Feel free to do so if you wanna give it a go!

**Pull request merged**
